// Seeds the locations collection from seed-data/locations.json.
//
// The fixture is generated by scripts/fetchOpenData.js using NYC Open Data
// (museums fn6f-htvy, parks enfh-gkve, DOHMH restaurants/cafes 43nn-pn8j).
// Re-run that script to refresh the fixture; this script just loads it.
//
// Only dataset-seeded locations (addedBy: null) are removed before insert,
// so user-suggested locations from running sessions survive a reseed.

import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { dbConnection, closeConnection } from './config/mongoConnection.js';
import { locations } from './config/mongoCollections.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FIXTURE_PATH = path.join(__dirname, 'seed-data', 'locations.json');

async function seed() {
  const raw = await fs.readFile(FIXTURE_PATH, 'utf8');
  const fixture = JSON.parse(raw);

  const db = await dbConnection();
  console.log(`Seeding "${db.databaseName}" from ${path.relative(__dirname, FIXTURE_PATH)}`);

  const locationsCol = await locations();
  const dropped = await locationsCol.deleteMany({ addedBy: null });
  console.log(`Removed ${dropped.deletedCount} previously seeded location(s).`);

  const now = new Date();
  const docs = fixture.map((loc) => ({
    ...loc,
    averageRating: null,
    totalReviews: 0,
    addedBy: null,
    approved: true,
    createdAt: now
  }));

  const result = await locationsCol.insertMany(docs);
  console.log(`Inserted ${result.insertedCount} location(s).`);

  await closeConnection();
  console.log('Done.');
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
